name: Automatic generating docs for ðŸ“¦

on: workflow_dispatch


permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '{{cookiecutter.python_interpreter}}'
      - uses: actions/cache@v2
        with:
          {% raw %}
          key: ${{ github.ref }}
          {% endraw %}
          path: .cache

      - run: python -m pip install --upgrade pip
      - run: python -m pip install -e .
      - run: make docs_install
      - run: mkdocs gh-deploy --force
